//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlueprintEditor2.Resource {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BlueprintEditor2.Resource.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SE Blueprint Editor - program for editing blueprints of the game &quot;Space Engineers&quot; outside the game
        ///This program allows you to quickly change the necessary parts of the blueprints(blocks, their settings, etc.), without starting the game.
        ///Developed by clan &quot;Andromeda&quot;.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на About program.
        /// </summary>
        public static string AboutProg {
            get {
                return ResourceManager.GetString("AboutProg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на All.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Blueprint is already open.
        /// </summary>
        public static string AlreadyOpened {
            get {
                return ResourceManager.GetString("AlreadyOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Amount.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Assembler efficiency.
        /// </summary>
        public static string AssemblerEfficiency {
            get {
                return ResourceManager.GetString("AssemblerEfficiency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Backups.
        /// </summary>
        public static string Backups {
            get {
                return ResourceManager.GetString("Backups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Block color.
        /// </summary>
        public static string BlockColor {
            get {
                return ResourceManager.GetString("BlockColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Blocks.
        /// </summary>
        public static string BlockCount {
            get {
                return ResourceManager.GetString("BlockCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Block name.
        /// </summary>
        public static string BlockName {
            get {
                return ResourceManager.GetString("BlockName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Block subtype.
        /// </summary>
        public static string BlockSubtype {
            get {
                return ResourceManager.GetString("BlockSubtype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Block type.
        /// </summary>
        public static string BlockType {
            get {
                return ResourceManager.GetString("BlockType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Blueprints directory.
        /// </summary>
        public static string BlueFolder {
            get {
                return ResourceManager.GetString("BlueFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Blueprint.
        /// </summary>
        public static string Blueprint {
            get {
                return ResourceManager.GetString("Blueprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Calculate.
        /// </summary>
        public static string Calculate {
            get {
                return ResourceManager.GetString("Calculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Changed.
        /// </summary>
        public static string Changed {
            get {
                return ResourceManager.GetString("Changed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Coming soon....
        /// </summary>
        public static string ComingSoon {
            get {
                return ResourceManager.GetString("ComingSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bulletproof glass.
        /// </summary>
        public static string Component_BulletproofGlass {
            get {
                return ResourceManager.GetString("Component/BulletproofGlass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Canvas.
        /// </summary>
        public static string Component_Canvas {
            get {
                return ResourceManager.GetString("Component/Canvas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Computer.
        /// </summary>
        public static string Component_Computer {
            get {
                return ResourceManager.GetString("Component/Computer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Construction.
        /// </summary>
        public static string Component_Construction {
            get {
                return ResourceManager.GetString("Component/Construction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Detector.
        /// </summary>
        public static string Component_Detector {
            get {
                return ResourceManager.GetString("Component/Detector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Display.
        /// </summary>
        public static string Component_Display {
            get {
                return ResourceManager.GetString("Component/Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Explosives.
        /// </summary>
        public static string Component_Explosives {
            get {
                return ResourceManager.GetString("Component/Explosives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Girder.
        /// </summary>
        public static string Component_Girder {
            get {
                return ResourceManager.GetString("Component/Girder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Gravity generator.
        /// </summary>
        public static string Component_GravityGenerator {
            get {
                return ResourceManager.GetString("Component/GravityGenerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Interior plate.
        /// </summary>
        public static string Component_InteriorPlate {
            get {
                return ResourceManager.GetString("Component/InteriorPlate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Large tube.
        /// </summary>
        public static string Component_LargeTube {
            get {
                return ResourceManager.GetString("Component/LargeTube", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Medical.
        /// </summary>
        public static string Component_Medical {
            get {
                return ResourceManager.GetString("Component/Medical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Metal grid.
        /// </summary>
        public static string Component_MetalGrid {
            get {
                return ResourceManager.GetString("Component/MetalGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Motor.
        /// </summary>
        public static string Component_Motor {
            get {
                return ResourceManager.GetString("Component/Motor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Power cell.
        /// </summary>
        public static string Component_PowerCell {
            get {
                return ResourceManager.GetString("Component/PowerCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Radio communication.
        /// </summary>
        public static string Component_RadioCommunication {
            get {
                return ResourceManager.GetString("Component/RadioCommunication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reactor.
        /// </summary>
        public static string Component_Reactor {
            get {
                return ResourceManager.GetString("Component/Reactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Small tube.
        /// </summary>
        public static string Component_SmallTube {
            get {
                return ResourceManager.GetString("Component/SmallTube", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Solar cell.
        /// </summary>
        public static string Component_SolarCell {
            get {
                return ResourceManager.GetString("Component/SolarCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Steel plate.
        /// </summary>
        public static string Component_SteelPlate {
            get {
                return ResourceManager.GetString("Component/SteelPlate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Thrust.
        /// </summary>
        public static string Component_Thrust {
            get {
                return ResourceManager.GetString("Component/Thrust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Components.
        /// </summary>
        public static string Components {
            get {
                return ResourceManager.GetString("Components", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Copy to clipboard.
        /// </summary>
        public static string CopyToClipboard {
            get {
                return ResourceManager.GetString("CopyToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Created.
        /// </summary>
        public static string Created {
            get {
                return ResourceManager.GetString("Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Current version.
        /// </summary>
        public static string CurrentVer {
            get {
                return ResourceManager.GetString("CurrentVer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete all backups of all blueprints in this directory.
        /// </summary>
        public static string DeleteAllBackups {
            get {
                return ResourceManager.GetString("DeleteAllBackups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Destructible grid.
        /// </summary>
        public static string DestructibleGrid {
            get {
                return ResourceManager.GetString("DestructibleGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Directories.
        /// </summary>
        public static string Directories {
            get {
                return ResourceManager.GetString("Directories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Don&apos;t open blueprints when scanning.
        /// </summary>
        public static string DontOpenAllBlue {
            get {
                return ResourceManager.GetString("DontOpenAllBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Do empty work.
        /// </summary>
        public static string DowLangPack {
            get {
                return ResourceManager.GetString("DowLangPack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Downloading new version.
        /// </summary>
        public static string DownNewVer {
            get {
                return ResourceManager.GetString("DownNewVer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Faction.
        /// </summary>
        public static string Faction {
            get {
                return ResourceManager.GetString("Faction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Game directory.
        /// </summary>
        public static string GameFolder {
            get {
                return ResourceManager.GetString("GameFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Back.
        /// </summary>
        public static string GoBack {
            get {
                return ResourceManager.GetString("GoBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Home.
        /// </summary>
        public static string GoHome {
            get {
                return ResourceManager.GetString("GoHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Grids.
        /// </summary>
        public static string GridCount {
            get {
                return ResourceManager.GetString("GridCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Grid name.
        /// </summary>
        public static string GridName {
            get {
                return ResourceManager.GetString("GridName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Image files.
        /// </summary>
        public static string ImFiles {
            get {
                return ResourceManager.GetString("ImFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cobalt.
        /// </summary>
        public static string Ingot_Cobalt {
            get {
                return ResourceManager.GetString("Ingot/Cobalt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Gold.
        /// </summary>
        public static string Ingot_Gold {
            get {
                return ResourceManager.GetString("Ingot/Gold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Iron.
        /// </summary>
        public static string Ingot_Iron {
            get {
                return ResourceManager.GetString("Ingot/Iron", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Magnesium.
        /// </summary>
        public static string Ingot_Magnesium {
            get {
                return ResourceManager.GetString("Ingot/Magnesium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Nickel.
        /// </summary>
        public static string Ingot_Nickel {
            get {
                return ResourceManager.GetString("Ingot/Nickel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Platinum.
        /// </summary>
        public static string Ingot_Platinum {
            get {
                return ResourceManager.GetString("Ingot/Platinum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Silicon.
        /// </summary>
        public static string Ingot_Silicon {
            get {
                return ResourceManager.GetString("Ingot/Silicon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Silver.
        /// </summary>
        public static string Ingot_Silver {
            get {
                return ResourceManager.GetString("Ingot/Silver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Gravel.
        /// </summary>
        public static string Ingot_Stone {
            get {
                return ResourceManager.GetString("Ingot/Stone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Uranium.
        /// </summary>
        public static string Ingot_Uranium {
            get {
                return ResourceManager.GetString("Ingot/Uranium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ingots.
        /// </summary>
        public static string Ingots {
            get {
                return ResourceManager.GetString("Ingots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Interface.
        /// </summary>
        public static string Interface {
            get {
                return ResourceManager.GetString("Interface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This action will delete the current blueprint file, do you really want to do this?.
        /// </summary>
        public static string ItWillDelete {
            get {
                return ResourceManager.GetString("ItWillDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This action will delete all backup files of all blueprints, do you really want to do this?.
        /// </summary>
        public static string ItWillDeleteAllBackps {
            get {
                return ResourceManager.GetString("ItWillDeleteAllBackps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Large grid.
        /// </summary>
        public static string LargeGrid {
            get {
                return ResourceManager.GetString("LargeGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Menu.
        /// </summary>
        public static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Multi-Window.
        /// </summary>
        public static string MultiWindow {
            get {
                return ResourceManager.GetString("MultiWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на None.
        /// </summary>
        public static string Nobody {
            get {
                return ResourceManager.GetString("Nobody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No thumbnail.
        /// </summary>
        public static string NoPic {
            get {
                return ResourceManager.GetString("NoPic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Looks like this blueprint doesn&apos;t have a thumbnail!
        ///Do you want set a thumbnail?
        ///Cancel - Don&apos;t set default thumbnail.
        /// </summary>
        public static string NoPicture {
            get {
                return ResourceManager.GetString("NoPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Normalize thumbnail (fix transparency).
        /// </summary>
        public static string Normalize {
            get {
                return ResourceManager.GetString("Normalize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cobalt.
        /// </summary>
        public static string Ore_Cobalt {
            get {
                return ResourceManager.GetString("Ore/Cobalt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Gold.
        /// </summary>
        public static string Ore_Gold {
            get {
                return ResourceManager.GetString("Ore/Gold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Iron.
        /// </summary>
        public static string Ore_Iron {
            get {
                return ResourceManager.GetString("Ore/Iron", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Magnesium.
        /// </summary>
        public static string Ore_Magnesium {
            get {
                return ResourceManager.GetString("Ore/Magnesium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Nickel.
        /// </summary>
        public static string Ore_Nickel {
            get {
                return ResourceManager.GetString("Ore/Nickel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Platinum.
        /// </summary>
        public static string Ore_Platinum {
            get {
                return ResourceManager.GetString("Ore/Platinum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Silicon.
        /// </summary>
        public static string Ore_Silicon {
            get {
                return ResourceManager.GetString("Ore/Silicon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Silver.
        /// </summary>
        public static string Ore_Silver {
            get {
                return ResourceManager.GetString("Ore/Silver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Stone.
        /// </summary>
        public static string Ore_Stone {
            get {
                return ResourceManager.GetString("Ore/Stone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Uranium.
        /// </summary>
        public static string Ore_Uranium {
            get {
                return ResourceManager.GetString("Ore/Uranium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ores.
        /// </summary>
        public static string Ores {
            get {
                return ResourceManager.GetString("Ores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Author.
        /// </summary>
        public static string Owner {
            get {
                return ResourceManager.GetString("Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings saved! For apply settings need to restart app,you want to restart the app?.
        /// </summary>
        public static string PleaseRestartApp {
            get {
                return ResourceManager.GetString("PleaseRestartApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please wait,  it&apos;s just that our servers work on potato electricity.
        /// </summary>
        public static string PleaseWaitServers {
            get {
                return ResourceManager.GetString("PleaseWaitServers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Properties.
        /// </summary>
        public static string Properties {
            get {
                return ResourceManager.GetString("Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Property.
        /// </summary>
        public static string Property {
            get {
                return ResourceManager.GetString("Property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enabled.
        /// </summary>
        public static string Property_Enabled {
            get {
                return ResourceManager.GetString("Property/Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show in inventory.
        /// </summary>
        public static string Property_ShowInInventory {
            get {
                return ResourceManager.GetString("Property/ShowInInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show in terminal.
        /// </summary>
        public static string Property_ShowInTerminal {
            get {
                return ResourceManager.GetString("Property/ShowInTerminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show in toolbar config.
        /// </summary>
        public static string Property_ShowInToolbarConfig {
            get {
                return ResourceManager.GetString("Property/ShowInToolbarConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show on HUD.
        /// </summary>
        public static string Property_ShowOnHUD {
            get {
                return ResourceManager.GetString("Property/ShowOnHUD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Remind me later.
        /// </summary>
        public static string RemLater {
            get {
                return ResourceManager.GetString("RemLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Replace by current.
        /// </summary>
        public static string ReplaceByCurrent {
            get {
                return ResourceManager.GetString("ReplaceByCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Restore.
        /// </summary>
        public static string Restore {
            get {
                return ResourceManager.GetString("Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save and сlose.
        /// </summary>
        public static string SaveClose {
            get {
                return ResourceManager.GetString("SaveClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please select blueprint to display information.
        /// </summary>
        public static string SelectBlue {
            get {
                return ResourceManager.GetString("SelectBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please select blueprint to open folder.
        /// </summary>
        public static string SelectBlueForOpen {
            get {
                return ResourceManager.GetString("SelectBlueForOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please select blueprints directory, usually it C:\Users\%UserName%\AppData\Roaming\SpaceEngineers
        ///\Blueprints\local.
        /// </summary>
        public static string SelectBluePatchDesc {
            get {
                return ResourceManager.GetString("SelectBluePatchDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please select game directory, usually it C:\Program Files (x86)\Steam
        ///\SteamApps\common\SpaceEngineers.
        /// </summary>
        public static string SelectGamePatchDesc {
            get {
                return ResourceManager.GetString("SelectGamePatchDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please select item to display information.
        /// </summary>
        public static string SelectOne {
            get {
                return ResourceManager.GetString("SelectOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Share mode.
        /// </summary>
        public static string ShareMode {
            get {
                return ResourceManager.GetString("ShareMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Small grid.
        /// </summary>
        public static string SmallGrid {
            get {
                return ResourceManager.GetString("SmallGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Stone amount (kg).
        /// </summary>
        public static string StoneAmount {
            get {
                return ResourceManager.GetString("StoneAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на System.
        /// </summary>
        public static string System {
            get {
                return ResourceManager.GetString("System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на System.
        /// </summary>
        public static string SystemLang {
            get {
                return ResourceManager.GetString("SystemLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Undefined types.
        /// </summary>
        public static string UndefinedTypes {
            get {
                return ResourceManager.GetString("UndefinedTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This block types not found:.
        /// </summary>
        public static string UndefinedTypesExists {
            get {
                return ResourceManager.GetString("UndefinedTypesExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unsafe action.
        /// </summary>
        public static string UnsafeAction {
            get {
                return ResourceManager.GetString("UnsafeAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Available version.
        /// </summary>
        public static string UpdateAvailable {
            get {
                return ResourceManager.GetString("UpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Update now (auto).
        /// </summary>
        public static string UpdateNow {
            get {
                return ResourceManager.GetString("UpdateNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на View blueprint folder.
        /// </summary>
        public static string ViewFold {
            get {
                return ResourceManager.GetString("ViewFold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на What&apos;s new:.
        /// </summary>
        public static string WhatNew {
            get {
                return ResourceManager.GetString("WhatNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Yield modules.
        /// </summary>
        public static string YieldModules {
            get {
                return ResourceManager.GetString("YieldModules", resourceCulture);
            }
        }
    }
}
